language: cpp
sudo: required
dist: trusty
compiler:
    - clang
    - gcc
os:
    - linux
    - osx
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
before_install:
    - echo $LANG
    - echo $LC_ALL
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -qq update && sudo apt-get -qq install software-properties-common && sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -qq update && sudo apt-get -qq install software-properties-common build-essential clang-3.8 llvm-3.9-dev valgrind curl libboost-all-dev lcov; fi
    - if [ $TRAVIS_OS_NAME == osx ]; then brew update --quiet && brew install llvm && eval "$(pyenv init -)" && pyenv install 2.7.6 && pyenv global 2.7.6 && pyenv rehash; fi
    - pip install --user cpp-coveralls
    - $CXX --version
before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC
script:
    - sudo make -j2
    - make hyperscale-coverage
after_success: coveralls --exclude test --gcov-options '\-lp'
after_failure: cat Testing/Temporary/LastTest.log
branches:
  only:
    - master
    - "/^v\\d+\\./"
