language: cpp

sudo: required

dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7
            - llvm-5.0-dev
            - valgrind
            - curl
            - libboost-all-dev
            - lcov
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - llvm-5.0-dev
            - valgrind
            - curl
            - libboost-all-dev
            - lcov
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew update && brew install -f gcc && pyenv install 2.7.6 && pyenv global 2.7.6 && pyenv rehash && CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew update && brew install -f llvm && pyenv install 2.7.6 && pyenv global 2.7.6 && pyenv rehash && CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"
  - echo $LANG
  - echo $LC_ALL
  - pip install --user cpp-coveralls
  - $CXX --version

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC

script:
  - sudo make && make hyperscale-coverage

after_success: coveralls --exclude test --gcov-options '\-lp'
after_failure: cat Testing/Temporary/LastTest.log

branches:
  only:
    - master
    - "/^v\\d+\\./"
