# Description:
#   Bazel build file for WTF.

cc_library(
    name = "wtf",
    srcs = glob([
        "wtf/**/*.cpp",
    ]),
    hdrs = glob([
        "wtf/**/*.h",
        "*.h"
    ]),
    visibility = ["//main:__pkg__"],
)
