cc_library(
    name = "hyperscale",
    srcs = glob(["hyperscale/**/*.cpp"]),
    hdrs = glob(["include/**/*.hpp"]),
    copts = ["-Iinclude/"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "einfo",
    srcs = glob(["libeiinfo/src/*.c"]),
    hdrs = glob(["libeiinfo/src/*.h"]),
    visibility = ["//visibility:public"],
)
