on: push
name: CI
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: bazelbuild/setup-bazelisk@v1

    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: "~/.cache/bazel"
        key: bazel

    - name: Install packages
      run: sudo apt-get install -yq git wget build-essential python3 clang

    - name: Building
      run: bazel build //...

    - name: Testing
      run: bazel test //test:hyperscale-test
